### ISSUE TITLE
Change relative imports to absolute imports

### ISSUE THREAD

**Issue by Dawid-Sroka** [Problematy/goodmap#111]
I read that absolute imports are recommended over relative imports in Python:
https://peps.python.org/pep-0008/#imports

Was there any particular reason why relative imports were used in our code? Here:
https://github.com/Problematy/goodmap/blob/62c62a1c0ec952a5107bede349cd75ba8fd53882/goodmap/core_api.py#L6C1-L7C35
and here:
https://github.com/Problematy/goodmap/blob/62c62a1c0ec952a5107bede349cd75ba8fd53882/goodmap/goodmap.py#L6C1-L8C1

**Comment by raven-wing** [comment]
If that will work - I see no harm in doing so.
Would you take that @Dawid-Sroka ?
