### ISSUE TITLE
FEATURE: change the width of the top menu bar

### ISSUE THREAD

**Issue by AgaFra** [Problematy/goodmap#125]
Top menu bar is wide, may limit visibility. 

The option to set the height of a bar or adjust it to the menu items could be added so that it doesn’t take up more space than needed.

**Comment by raven-wing** [comment]
If that's from audit it probably should be height? @AgaFra am I right?

**Comment by AgaFra** [comment]
True, height, the screenshot below, and I corrected the description.
![image](https://github.com/user-attachments/assets/fb12f0d6-0791-437b-8134-3a24ccbe41dc)
