### ISSUE TITLE
BUG: language change works only on main/map page

### ISSUE THREAD

**Issue by AgaFra** [Problematy/goodmap#127]
**Describe the bug**
Changing the language does not work on the top panel as well as on any of the subpages.

**To Reproduce**
1. Go to https://www.rzutberetem.eco/blog/page/about-us
2. Click on flag icon to change for english or українська
3. See error

**Expected behavior**
Change language to English or українська in the whole site (including top bar menu and all subpages) after selecting the appropriate language.

**Screenshots**
![image](https://github.com/user-attachments/assets/54840f2e-62b2-4c6a-9ac3-8601ad6b62bc)

![image](https://github.com/user-attachments/assets/03f15783-7cd8-40e5-b5ca-6ac85117b6a4)

**Comment by x-Milosz** [comment]
As we checked during the work, the translation mechanisms are working correctly, so that there are simply no corresponding translations.

**Comment by raven-wing** [comment]
Closed with #182
