### ISSUE TITLE
FEATURE: Collapsible answers in FAQ

### ISSUE THREAD

**Issue by AgaFra** [Problematy/goodmap#128]
**Is your feature request related to a problem? Please describe.**
The FAQ section is a single wall of text, highlighted by bold questions and spacing between them. This makes the content overwhelming and it is difficult to see which question interests the user.

**Describe the solution you'd like**
Implement a solution in which only the questions are visible and after clicking on them (or the icon indicating the development) the answers will appear.

![image](https://github.com/user-attachments/assets/45b03b93-4e56-424b-8320-035a34541121)

**Comment by x-Milosz** [comment]
I have no acces to the jsons of rzutberetem but I think we can just move FAQ questions to html tags, in such way for example: 
<details><summary>Question 1: What is Markdown?</summary> Markdown is a lightweight markup language for creating formatted text using a plain-text editor.</details>
