### ISSUE TITLE
FEATURE: CTA buttons

### ISSUE THREAD

**Issue by AgaFra** [Problematy/goodmap#129]
**Is your feature request related to a problem? Please describe.**
Outgoing links are marked on the logs/pictures, so a user has to guess that they should click on the logo to go to a specific address.

**Describe the solution you'd like**
Implement Implement CTA buttons in subpages

![image](https://github.com/user-attachments/assets/d1c51e14-6a48-4434-aba4-2eee31a6ae7e)

**Comment by x-Milosz** [comment]
I have no acces to the jsons of rzutberetem but I think we can just move links to button images and center them.
Like here:
[![Click Me](https://via.placeholder.com/150x50?text=Click+Me)](https://example.com)

**Comment by AgaFra** [comment]
changes applied to data file
