### ISSUE TITLE
BUG: data in pin is not checked

### ISSUE THREAD

**Issue by raven-wing** [Problematy/goodmap#152]
**Describe the bug**
E2E test doesn't check data at all

**To Reproduce**
1.  run `make run-e2e-env`
2. check http://www.localhost:5000/

**Expected behavior**
good data is visible, and there is test which checkes it.

**Screenshots**
![2024-10-09-230903_215x217_scrot](https://github.com/user-attachments/assets/04138f7d-6817-4017-b075-230eef6990c9)

**Comment by raven-wing** [comment]
@Dawid-Sroka it was introduced with #149.
Please run code with e2e tests : `make e2e-tests` and fix it accordingly to describtion

**Comment by Dawid-Sroka** [comment]
I think this should be closed just like https://github.com/Problematy/goodmap-frontend/issues/58

**Comment by raven-wing** [comment]
No, but  #164 includes changes that are closing this issue.
