### ISSUE TITLE
FEATURE: Add representation of CTAs to the points

### ISSUE THREAD

**Issue by Dawid-Sroka** [Problematy/goodmap#156]
We want some points on a map to have a CTA.
Information about whether a point has a CTA and what is its type (url, other?), its content etc., should be added to the database.
This change in database should be reflected in the API of sending data to frontend.

The question is how to represent the CTA in the database.
Should it be a point's attribute? A metadata? Data?

The task is to propose a representation of CTA in the database, handle it in the backend and include it in the frontend API.

What we want in the end is probably something like this:
![CTA_proposition](https://github.com/user-attachments/assets/fd956e61-695e-4c5d-84e8-34f1f75e10fb)

**Comment by raven-wing** [comment]
It should be like in website.
```

               "website": {
                   "type": "hyperlink",
                   "value": "https://www.kappahl.com/pl-pl/zrownowaony-rozwoj/nasze-zbiorki-tekstyliow",
                   "displayValue": "kappahl.com"
                },
```

This should probably be enaugh:

```

               "CTA": {
                   "type": "button",
                   "url": "<address-to-page>",
                   "displayValue": "<Call to action>"
                },
```

**Comment by raven-wing** [comment]
Won't fix because it was fixed in https://github.com/Problematy/goodmap-frontend/pull/62
