### ISSUE TITLE
Element '<title>' must not be empty

### ISSUE THREAD

**Issue by KingaWitkoAccessibility** [Problematy/goodmap#88]
**Website:** https://www.rzutberetem.eco/ and sub pages

**Description:**
rzutberetem.eco and sub pages don't have '<title>'
`From line 1, column 1953; to line 1, column 1960s"><title></title><meta`

**Expected result:**
Element '<title>' must not be empty
The title could be for example "Rzut beretem or Project Rzut beretem

**Comment by x-Milosz** [comment]
I see that title tag is not empty and properly filled.
![image](https://github.com/user-attachments/assets/1c4a305a-bae8-4b6f-b254-e14160037755)
